# Generated by Django 3.2.3 on 2021-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=20)),
                ('korisnicko_ime', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('sifra', models.CharField(max_length=30)),
                ('tip_korisnika', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('slika', models.CharField(max_length=50)),
            ],
        ),
    ]
