# Generated by Django 3.2.3 on 2021-06-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('termin_predavanja', models.TimeField()),
                ('termin_vjezbi', models.TimeField()),
                ('godina', models.IntegerField()),
                ('semestar', models.IntegerField()),
                ('asistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistent', to='dws.korisnik')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to='dws.korisnik')),
            ],
        ),
    ]
