# Generated by Django 3.2.3 on 2021-06-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dws', '0002_predmet'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadOdKuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zahtjev', models.CharField(max_length=20)),
                ('datum', models.DateField()),
                ('razlozi', models.CharField(max_length=200)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dws.korisnik')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dws.predmet')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('vrsta', models.CharField(max_length=30)),
                ('pocetak', models.TimeField()),
                ('kraj', models.TimeField()),
                ('broj_studenata', models.IntegerField()),
                ('sedmica', models.IntegerField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dws.korisnik')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dws.predmet')),
            ],
        ),
    ]
